# SPDX-FileCopyrightText: 2014 SAP SE Srdjan Boskovic <srdjan.boskovic@sap.com>
#
# SPDX-License-Identifier: Apache-2.0

import pytest
from pyshlp import *
from abapsystems import *

#
# I64 CT Helps
#

c = get_connection(I64)

vih = valueInput(c)


# CT Test
#

#CT T16FB

def test_CT_T16FB():

    r = vih.get_shelp_descriptor('CT T16FB')

    assert r['elementary_helps'] ==  {u'CT T16FB': {'FIELDDESCR': [{u'AUTHORID': u'',
                                                                    u'BIDICTRLC': u'',
                                                                    u'CHECKTABLE': u'',
                                                                    u'COMPTYPE': u'E',
                                                                    u'CONVEXIT': u'',
                                                                    u'DATATYPE': u'CHAR',
                                                                    u'DECIMALS': 0,
                                                                    u'DOMNAME': u'FRGKE',
                                                                    u'DYNPFLD': u'X',
                                                                    u'F4AVAILABL': u'',
                                                                    u'FIELDNAME': u'FRGKE',
                                                                    u'FIELDTEXT': u'Release Indicator: Purchasing Document',
                                                                    u'GENKEY': u'',
                                                                    u'HEADLEN': 3,
                                                                    u'INTLEN': 2,
                                                                    u'INTTYPE': u'C',
                                                                    u'KEYFLAG': u'X',
                                                                    u'LANGU': u'E',
                                                                    u'LENG': 1,
                                                                    u'LFIELDNAME': u'FRGKE',
                                                                    u'LOGFLAG': u'X',
                                                                    u'LOWERCASE': u'',
                                                                    u'LTRFLDDIS': u'',
                                                                    u'MAC': u'',
                                                                    u'MASK': u'',
                                                                    u'MASKLEN': u'0000',
                                                                    u'MEMORYID': u'',
                                                                    u'NOAUTHCH': u'',
                                                                    u'NOFORKEY': u'',
                                                                    u'OFFSET': 6,
                                                                    u'OUTPUTLEN': 1,
                                                                    'PARTXT': '',
                                                                    'PARVA': '',
                                                                    u'POSITION': 1,
                                                                    u'PRECFIELD': u'T16FB',
                                                                    u'REFFIELD': u'',
                                                                    u'REFTABLE': u'',
                                                                    u'REPTEXT': u'Rel',
                                                                    u'ROLLNAME': u'FRGKE',
                                                                    u'SCRLEN1': 8,
                                                                    u'SCRLEN2': 13,
                                                                    u'SCRLEN3': 19,
                                                                    u'SCRTEXT_L': u'Release indicator',
                                                                    u'SCRTEXT_M': u'Release ind.',
                                                                    u'SCRTEXT_S': u'Release',
                                                                    u'SIGN': u'',
                                                                    u'TABNAME': u'T16FB',
                                                                    'TOPSHLPFLD': u'',
                                                                    'TOPSHLPNAM': u'',
                                                                    u'VALEXI': u''}],
                                                    'INTDESCR': {u'DDLANGUAGE': u'',
                                                                 u'DDTEXT': u'',
                                                                 u'DIALOGINFO': u'X',
                                                                 u'DIALOGTYPE': u'D',
                                                                 u'F4STATE': u'',
                                                                 u'FIELDNAME': u'',
                                                                 u'HANDLE': 0,
                                                                 u'HISTORY': u'',
                                                                 u'HOTKEY': u'',
                                                                 u'ISSIMPLE': u'X',
                                                                 u'SELMETHOD': u'T16FB',
                                                                 u'SELMEXIT': u'',
                                                                 u'SELMTYPE': u'',
                                                                 u'TABNAME': u'',
                                                                 u'TEXTTAB': u'',
                                                                 u'TITLE': u''},
                                                    'SCRLENMAX': 19,
                                                    'SHLPOUTPUT': u'FRGKE'}}




    sel = []
    r = vih.search('CT T16FB', sel)
    # _todo: corrupted in test system :-(
    # assert r['headers'] == [[u'FRGKE', u'Rel', 1], [u'FRGET', u'Description', 30]]
    # assert r['search_result'] == [{u'FRGET': u'Blocked, changeable with value', u'FRGKE': u'B'},
    #                              {u'FRGET': u'Released', u'FRGKE': u'G'},
    #                              {u'FRGET': u'Released, no changes', u'FRGKE': u'R'}]
    ''' assert r['desc'] == [{u'AUTHORID': u'',
                          u'BIDICTRLC': u'',
                          u'CHECKTABLE': u'',
                          u'COMPTYPE': u'E',
                          u'CONVEXIT': u'',
                          u'DATATYPE': u'CHAR',
                          u'DECIMALS': u'000000',
                          u'DOMNAME': u'FRGKE',
                          u'DYNPFLD': u'X',
                          u'F4AVAILABL': u'',
                          u'FIELDNAME': u'FRGKE',
                          u'FIELDTEXT': u'Release Indicator: Purchasing Document',
                          u'GENKEY': u'',
                          u'HEADLEN': u'03',
                          u'INTLEN': u'000002',
                          u'INTTYPE': u'C',
                          u'KEYFLAG': u'X',
                          u'LANGU': u'E',
                          u'LENG': u'000001',
                          u'LFIELDNAME': u'FRGKE',
                          u'LOGFLAG': u'X',
                          u'LOWERCASE': u'',
                          u'LTRFLDDIS': u'',
                          u'MAC': u'',
                          u'MASK': u'',
                          u'MASKLEN': u'0000',
                          u'MEMORYID': u'',
                          u'NOAUTHCH': u'',
                          u'NOFORKEY': u'',
                          u'OFFSET': u'000006',
                          u'OUTPUTLEN': u'000001',
                          u'POSITION': u'0001',
                          u'PRECFIELD': u'T16FB',
                          u'REFFIELD': u'',
                          u'REFTABLE': u'',
                          u'REPTEXT': u'Rel',
                          u'ROLLNAME': u'FRGKE',
                          u'SCRLEN1': u'08',
                          u'SCRLEN2': u'13',
                          u'SCRLEN3': u'19',
                          u'SCRTEXT_L': u'Release indicator',
                          u'SCRTEXT_M': u'Release ind.',
                          u'SCRTEXT_S': u'Release',
                          u'SIGN': u'',
                          u'TABNAME': u'T16FB',
                          u'VALEXI': u''},
                         {u'AUTHORID': u'',
                          u'BIDICTRLC': u'',
                          u'CHECKTABLE': u'',
                          u'COMPTYPE': u'E',
                          u'CONVEXIT': u'',
                          u'DATATYPE': u'CHAR',
                          u'DECIMALS': u'000000',
                          u'DOMNAME': u'TEXT30',
                          u'DYNPFLD': u'X',
                          u'F4AVAILABL': u'',
                          u'FIELDNAME': u'FRGET',
                          u'FIELDTEXT': u'Description of Release Indicator',
                          u'GENKEY': u'',
                          u'HEADLEN': u'30',
                          u'INTLEN': u'000060',
                          u'INTTYPE': u'C',
                          u'KEYFLAG': u'X',
                          u'LANGU': u'E',
                          u'LENG': u'000030',
                          u'LFIELDNAME': u'FRGET',
                          u'LOGFLAG': u'',
                          u'LOWERCASE': u'X',
                          u'LTRFLDDIS': u'',
                          u'MAC': u'',
                          u'MASK': u'',
                          u'MASKLEN': u'0000',
                          u'MEMORYID': u'',
                          u'NOAUTHCH': u'',
                          u'NOFORKEY': u'',
                          u'OFFSET': u'000008',
                          u'OUTPUTLEN': u'000030',
                          u'POSITION': u'0002',
                          u'PRECFIELD': u'T16FE',
                          u'REFFIELD': u'',
                          u'REFTABLE': u'',
                          u'REPTEXT': u'Description',
                          u'ROLLNAME': u'FRGET',
                          u'SCRLEN1': u'09',
                          u'SCRLEN2': u'11',
                          u'SCRLEN3': u'11',
                          u'SCRTEXT_L': u'Description',
                          u'SCRTEXT_M': u'Description',
                          u'SCRTEXT_S': u'Descr.',
                          u'SIGN': u'',
                          u'TABNAME': u'T16FE',
                          u'VALEXI': u''}]
    '''
    assert r['maxrows_exceeded'] == ''
    assert r['shlpoutput'] == 'FRGKE'




def test_CT_T165R():

    r = vih.get_shelp_descriptor('CT T165R')
    assert r['elementary_helps'] == {u'CT T165R': {'FIELDDESCR': [{u'AUTHORID': u'',
                                                                   u'BIDICTRLC': u'',
                                                                   u'CHECKTABLE': u'',
                                                                   u'COMPTYPE': u'E',
                                                                   u'CONVEXIT': u'',
                                                                   u'DATATYPE': u'NUMC',
                                                                   u'DECIMALS': 0,
                                                                   u'DOMNAME': u'NUMC02',
                                                                   u'DYNPFLD': u'X',
                                                                   u'F4AVAILABL': u'',
                                                                   u'FIELDNAME': u'ABSGR',
                                                                   u'FIELDTEXT': u'Reason for Cancellation',
                                                                   u'GENKEY': u'',
                                                                   u'HEADLEN': 11,
                                                                   u'INTLEN': 4,
                                                                   u'INTTYPE': u'N',
                                                                   u'KEYFLAG': u'X',
                                                                   u'LANGU': u'E',
                                                                   u'LENG': 2,
                                                                   u'LFIELDNAME': u'ABSGR',
                                                                   u'LOGFLAG': u'X',
                                                                   u'LOWERCASE': u'',
                                                                   u'LTRFLDDIS': u'',
                                                                   u'MAC': u'',
                                                                   u'MASK': u'',
                                                                   u'MASKLEN': u'0000',
                                                                   u'MEMORYID': u'',
                                                                   u'NOAUTHCH': u'',
                                                                   u'NOFORKEY': u'',
                                                                   u'OFFSET': 6,
                                                                   u'OUTPUTLEN': 2,
                                                                   'PARTXT': '',
                                                                   'PARVA': '',
                                                                   u'POSITION': 1,
                                                                   u'PRECFIELD': u'T165R',
                                                                   u'REFFIELD': u'',
                                                                   u'REFTABLE': u'',
                                                                   u'REPTEXT': u'Reas. Canc.',
                                                                   u'ROLLNAME': u'ABSGR',
                                                                   u'SCRLEN1': 10,
                                                                   u'SCRLEN2': 15,
                                                                   u'SCRLEN3': 20,
                                                                   u'SCRTEXT_L': u'Reason for Canc.',
                                                                   u'SCRTEXT_M': u'Reas. for Canc.',
                                                                   u'SCRTEXT_S': u'Reas.Canc.',
                                                                   u'SIGN': u'',
                                                                   u'TABNAME': u'T165R',
                                                                   'TOPSHLPFLD': u'',
                                                                   'TOPSHLPNAM': u'',
                                                                   u'VALEXI': u''}],
                                                   'INTDESCR': {u'DDLANGUAGE': u'',
                                                                u'DDTEXT': u'',
                                                                u'DIALOGINFO': u'X',
                                                                u'DIALOGTYPE': u'D',
                                                                u'F4STATE': u'',
                                                                u'FIELDNAME': u'',
                                                                u'HANDLE': 0,
                                                                u'HISTORY': u'',
                                                                u'HOTKEY': u'',
                                                                u'ISSIMPLE': u'X',
                                                                u'SELMETHOD': u'T165R',
                                                                u'SELMEXIT': u'',
                                                                u'SELMTYPE': u'',
                                                                u'TABNAME': u'',
                                                                u'TEXTTAB': u'',
                                                                u'TITLE': u''},
                                                   'SCRLENMAX': 20,
                                                   'SHLPOUTPUT': u'ABSGR'}}


    sel = []

    r = vih.search('CT T165R', sel)
    # _todo: corrupted in test system :-(
    # assert r['headers'] == [[u'ABSGR', u'Reas. Canc.', 2], [u'ABSGR_TXT', u'Name', 40]]
    #assert r['search_result'] == [{u'ABSGR': u'01',u'ABSGR_TXT': u'Cancelled due to poor quality'},
    #                              {u'ABSGR': u'02', u'ABSGR_TXT': u'Cancelled - source of supply changed'}]
    assert r['shlpoutput'] == u'ABSGR'
    '''
    assert r['desc'] == [{u'AUTHORID': u'',
                          u'BIDICTRLC': u'',
                          u'CHECKTABLE': u'',
                          u'COMPTYPE': u'E',
                          u'CONVEXIT': u'',
                          u'DATATYPE': u'NUMC',
                          u'DECIMALS': u'000000',
                          u'DOMNAME': u'NUMC02',
                          u'DYNPFLD': u'X',
                          u'F4AVAILABL': u'',
                          u'FIELDNAME': u'ABSGR',
                          u'FIELDTEXT': u'Reason for Cancellation',
                          u'GENKEY': u'',
                          u'HEADLEN': u'11',
                          u'INTLEN': u'000004',
                          u'INTTYPE': u'N',
                          u'KEYFLAG': u'X',
                          u'LANGU': u'E',
                          u'LENG': u'000002',
                          u'LFIELDNAME': u'ABSGR',
                          u'LOGFLAG': u'X',
                          u'LOWERCASE': u'',
                          u'LTRFLDDIS': u'',
                          u'MAC': u'',
                          u'MASK': u'',
                          u'MASKLEN': u'0000',
                          u'MEMORYID': u'',
                          u'NOAUTHCH': u'',
                          u'NOFORKEY': u'',
                          u'OFFSET': u'000006',
                          u'OUTPUTLEN': u'000002',
                          u'POSITION': u'0002',
                          u'PRECFIELD': u'T165R',
                          u'REFFIELD': u'',
                          u'REFTABLE': u'',
                          u'REPTEXT': u'Reas. Canc.',
                          u'ROLLNAME': u'ABSGR',
                          u'SCRLEN1': u'10',
                          u'SCRLEN2': u'15',
                          u'SCRLEN3': u'20',
                          u'SCRTEXT_L': u'Reason for Canc.',
                          u'SCRTEXT_M': u'Reas. for Canc.',
                          u'SCRTEXT_S': u'Reas.Canc.',
                          u'SIGN': u'',
                          u'TABNAME': u'T165R',
                          u'VALEXI': u''},
                         {u'AUTHORID': u'',
                          u'BIDICTRLC': u'',
                          u'CHECKTABLE': u'',
                          u'COMPTYPE': u'E',
                          u'CONVEXIT': u'',
                          u'DATATYPE': u'CHAR',
                          u'DECIMALS': u'000000',
                          u'DOMNAME': u'TEXT40',
                          u'DYNPFLD': u'X',
                          u'F4AVAILABL': u'',
                          u'FIELDNAME': u'ABSGR_TXT',
                          u'FIELDTEXT': u'Text, 40 Characters Long',
                          u'GENKEY': u'',
                          u'HEADLEN': u'40',
                          u'INTLEN': u'000080',
                          u'INTTYPE': u'C',
                          u'KEYFLAG': u'X',
                          u'LANGU': u'E',
                          u'LENG': u'000040',
                          u'LFIELDNAME': u'ABSGR_TXT',
                          u'LOGFLAG': u'',
                          u'LOWERCASE': u'X',
                          u'LTRFLDDIS': u'',
                          u'MAC': u'',
                          u'MASK': u'',
                          u'MASKLEN': u'0000',
                          u'MEMORYID': u'',
                          u'NOAUTHCH': u'',
                          u'NOFORKEY': u'',
                          u'OFFSET': u'000010',
                          u'OUTPUTLEN': u'000040',
                          u'POSITION': u'0001',
                          u'PRECFIELD': u'T165M',
                          u'REFFIELD': u'',
                          u'REFTABLE': u'',
                          u'REPTEXT': u'Name',
                          u'ROLLNAME': u'TEXT40',
                          u'SCRLEN1': u'00',
                          u'SCRLEN2': u'00',
                          u'SCRLEN3': u'00',
                          u'SCRTEXT_L': u'',
                          u'SCRTEXT_M': u'',
                          u'SCRTEXT_S': u'',
                          u'SIGN': u'',
                          u'TABNAME': u'T165M',
                          u'VALEXI': u''}]
    '''

def test_CT_CSKS():

    r = vih.get_shelp_descriptor('CT CSKS')


    assert r['elementary_helps'] == {u'CT CSKS':
                {'FIELDDESCR': [{u'AUTHORID': u'',
                    u'BIDICTRLC': u'',
                    u'CHECKTABLE': u'',
                    u'COMPTYPE': u'E',
                    u'CONVEXIT': u'',
                    u'DATATYPE': u'DATS',
                    u'DECIMALS': 0,
                    u'DOMNAME': u'DATUM',
                    u'DYNPFLD': u'X',
                    u'F4AVAILABL': u'X',
                    u'FIELDNAME': u'DATBI',
                    u'FIELDTEXT': u'Valid To Date',
                    u'GENKEY': u'',
                    u'HEADLEN': 10,
                    u'INTLEN': 16,
                    u'INTTYPE': u'D',
                    u'KEYFLAG': u'X',
                    u'LANGU': u'E',
                    u'LENG': 8,
                    u'LFIELDNAME': u'DATBI',
                    u'LOGFLAG': u'X',
                    u'LOWERCASE': u'',
                    u'LTRFLDDIS': u'',
                    u'MAC': u'',
                    u'MASK': u'',
                    u'MASKLEN': u'0000',
                    u'MEMORYID': u'',
                    u'NOAUTHCH': u'',
                    u'NOFORKEY': u'',
                    u'OFFSET': 34,
                    u'OUTPUTLEN': 10,
                    'PARTXT': '',
                    'PARVA': '',
                    u'POSITION': 1,
                    u'PRECFIELD': u'CSKS',
                    u'REFFIELD': u'',
                    u'REFTABLE': u'',
                    u'REPTEXT': u'to',
                    u'ROLLNAME': u'DATBI',
                    u'SCRLEN1': 10,
                    u'SCRLEN2': 15,
                    u'SCRLEN3': 20,
                    u'SCRTEXT_L': u'Valid To',
                    u'SCRTEXT_M': u'Valid To',
                    u'SCRTEXT_S': u'to',
                    u'SIGN': u'',
                    u'TABNAME': u'CSKS',
                    'TOPSHLPFLD': u'',
                    'TOPSHLPNAM': u'',
                    u'VALEXI': u''},
                {u'AUTHORID': u'',
                    u'BIDICTRLC': u'',
                    u'CHECKTABLE': u'TKA01',
                    u'COMPTYPE': u'E',
                    u'CONVEXIT': u'',
                    u'DATATYPE': u'CHAR',
                    u'DECIMALS': 0,
                    u'DOMNAME': u'CACCD',
                    u'DYNPFLD': u'X',
                    u'F4AVAILABL': u'X',
                    u'FIELDNAME': u'KOKRS',
                    u'FIELDTEXT': u'Controlling Area',
                    u'GENKEY': u'',
                    u'HEADLEN': 4,
                    u'INTLEN': 8,
                    u'INTTYPE': u'C',
                    u'KEYFLAG': u'X',
                    u'LANGU': u'E',
                    u'LENG': 4,
                    u'LFIELDNAME': u'KOKRS',
                    u'LOGFLAG': u'X',
                    u'LOWERCASE': u'',
                    u'LTRFLDDIS': u'',
                    u'MAC': u'',
                    u'MASK': u'',
                    u'MASKLEN': u'0000',
                    u'MEMORYID': u'CAC',
                    u'NOAUTHCH': u'',
                    u'NOFORKEY': u'',
                    u'OFFSET': 6,
                    u'OUTPUTLEN': 4,
                    'PARTXT': '',
                    'PARVA': '',
                    u'POSITION': 2,
                    u'PRECFIELD': u'CSKS',
                    u'REFFIELD': u'',
                    u'REFTABLE': u'',
                    u'REPTEXT': u'COAr',
                    u'ROLLNAME': u'KOKRS',
                    u'SCRLEN1': 10,
                    u'SCRLEN2': 15,
                    u'SCRLEN3': 20,
                    u'SCRTEXT_L': u'Controlling Area',
                    u'SCRTEXT_M': u'CO Area',
                    u'SCRTEXT_S': u'CO Area',
                    u'SIGN': u'',
                    u'TABNAME': u'CSKS',
                    'TOPSHLPFLD': u'',
                    'TOPSHLPNAM': u'',
                    u'VALEXI': u''},
                {u'AUTHORID': u'',
                    u'BIDICTRLC': u'',
                    u'CHECKTABLE': u'',
                    u'COMPTYPE': u'E',
                    u'CONVEXIT': u'ALPHA',
                    u'DATATYPE': u'CHAR',
                    u'DECIMALS': 0,
                    u'DOMNAME': u'KOSTL',
                    u'DYNPFLD': u'X',
                    u'F4AVAILABL': u'X',
                    u'FIELDNAME': u'KOSTL',
                    u'FIELDTEXT': u'Cost Center',
                    u'GENKEY': u'',
                    u'HEADLEN': 10,
                    u'INTLEN': 20,
                    u'INTTYPE': u'C',
                    u'KEYFLAG': u'X',
                    u'LANGU': u'E',
                    u'LENG': 10,
                    u'LFIELDNAME': u'KOSTL',
                    u'LOGFLAG': u'X',
                    u'LOWERCASE': u'',
                    u'LTRFLDDIS': u'',
                    u'MAC': u'X',
                    u'MASK': u'',
                    u'MASKLEN': u'0000',
                    u'MEMORYID': u'KOS',
                    u'NOAUTHCH': u'',
                    u'NOFORKEY': u'',
                    u'OFFSET': 14,
                    u'OUTPUTLEN': 10,
                    'PARTXT': '',
                    'PARVA': '',
                    u'POSITION': 3,
                    u'PRECFIELD': u'CSKS',
                    u'REFFIELD': u'',
                    u'REFTABLE': u'',
                    u'REPTEXT': u'Cost Ctr',
                    u'ROLLNAME': u'KOSTL',
                    u'SCRLEN1': 10,
                    u'SCRLEN2': 15,
                    u'SCRLEN3': 20,
                    u'SCRTEXT_L': u'Cost Center',
                    u'SCRTEXT_M': u'Cost Center',
                    u'SCRTEXT_S': u'Cost Ctr',
                    u'SIGN': u'',
                    u'TABNAME': u'CSKS',
                    'TOPSHLPFLD': u'',
                    'TOPSHLPNAM': u'',
                    u'VALEXI': u''}],
                'INTDESCR': {u'DDLANGUAGE': u'',
                u'DDTEXT': u'',
                u'DIALOGINFO': u'X',
                u'DIALOGTYPE': u'D',
                u'F4STATE': u'',
                u'FIELDNAME': u'',
                u'HANDLE': 0,
                u'HISTORY': u'',
                u'HOTKEY': u'',
                u'ISSIMPLE': u'X',
                u'SELMETHOD': u'CSKS',
                u'SELMEXIT': u'',
                u'SELMTYPE': u'',
                u'TABNAME': u'',
                u'TEXTTAB': u'',
                u'TITLE': u''},
                'SCRLENMAX': 20,
                'SHLPOUTPUT': u'DATBI'}}

    eh = r['elementary_helps']['CT CSKS']

    assert eh['SCRLENMAX'] == 20
    assert eh['SHLPOUTPUT'] == 'DATBI'
    assert eh['INTDESCR'] == {  u'DDLANGUAGE': u'',
                                u'DDTEXT': u'',
                                u'DIALOGINFO': u'X',
                                u'DIALOGTYPE': u'D',
                                u'F4STATE': u'',
                                u'FIELDNAME': u'',
                                u'HANDLE': 0,
                                u'HISTORY': u'',
                                u'HOTKEY': u'',
                                u'ISSIMPLE': u'X',
                                u'SELMETHOD': u'CSKS',
                                u'SELMEXIT': u'',
                                u'SELMTYPE': u'',
                                u'TABNAME': u'',
                                u'TEXTTAB': u'',
                                u'TITLE': u''}

    assert eh['FIELDDESCR'][0] == { u'AUTHORID': u'',
                                    u'BIDICTRLC': u'',
                                    u'CHECKTABLE': u'',
                                    u'COMPTYPE': u'E',
                                    u'CONVEXIT': u'',
                                    u'DATATYPE': u'DATS',
                                    u'DECIMALS': 0,
                                    u'DOMNAME': u'DATUM',
                                    u'DYNPFLD': u'X',
                                    u'F4AVAILABL': u'X',
                                    u'FIELDNAME': u'DATBI',
                                    u'FIELDTEXT': u'Valid To Date',
                                    u'GENKEY': u'',
                                    u'HEADLEN': 10,
                                    u'INTLEN': 16,
                                    u'INTTYPE': u'D',
                                    u'KEYFLAG': u'X',
                                    u'LANGU': u'E',
                                    u'LENG': 8,
                                    u'LFIELDNAME': u'DATBI',
                                    u'LOGFLAG': u'X',
                                    u'LOWERCASE': u'',
                                    u'LTRFLDDIS': u'',
                                    u'MAC': u'',
                                    u'MASK': u'',
                                    u'MASKLEN': u'0000',
                                    u'MEMORYID': u'',
                                    u'NOAUTHCH': u'',
                                    u'NOFORKEY': u'',
                                    u'OFFSET': 34,
                                    u'OUTPUTLEN': 10,
                                    'PARTXT': '',
                                    'PARVA': '',
                                    u'POSITION': 1,
                                    u'PRECFIELD': u'CSKS',
                                    u'REFFIELD': u'',
                                    u'REFTABLE': u'',
                                    u'REPTEXT': u'to',
                                    u'ROLLNAME': u'DATBI',
                                    u'SCRLEN1': 10,
                                    u'SCRLEN2': 15,
                                    u'SCRLEN3': 20,
                                    u'SCRTEXT_L': u'Valid To',
                                    u'SCRTEXT_M': u'Valid To',
                                    u'SCRTEXT_S': u'to',
                                    u'SIGN': u'',
                                    u'TABNAME': u'CSKS',
                                    'TOPSHLPFLD': u'',
                                    'TOPSHLPNAM': u'',
                                    u'VALEXI': u''}



    assert eh['FIELDDESCR'][1] == { u'AUTHORID': u'',
                                    u'BIDICTRLC': u'',
                                    u'CHECKTABLE': u'TKA01',
                                    u'COMPTYPE': u'E',
                                    u'CONVEXIT': u'',
                                    u'DATATYPE': u'CHAR',
                                    u'DECIMALS': 0,
                                    u'DOMNAME': u'CACCD',
                                    u'DYNPFLD': u'X',
                                    u'F4AVAILABL': u'X',
                                    u'FIELDNAME': u'KOKRS',
                                    u'FIELDTEXT': u'Controlling Area',
                                    u'GENKEY': u'',
                                    u'HEADLEN': 4,
                                    u'INTLEN': 8,
                                    u'INTTYPE': u'C',
                                    u'KEYFLAG': u'X',
                                    u'LANGU': u'E',
                                    u'LENG': 4,
                                    u'LFIELDNAME': u'KOKRS',
                                    u'LOGFLAG': u'X',
                                    u'LOWERCASE': u'',
                                    u'LTRFLDDIS': u'',
                                    u'MAC': u'',
                                    u'MASK': u'',
                                    u'MASKLEN': u'0000',
                                    u'MEMORYID': u'CAC',
                                    u'NOAUTHCH': u'',
                                    u'NOFORKEY': u'',
                                    u'OFFSET': 6,
                                    u'OUTPUTLEN': 4,
                                    'PARTXT': '',
                                    'PARVA': '',
                                    u'POSITION': 2,
                                    u'PRECFIELD': u'CSKS',
                                    u'REFFIELD': u'',
                                    u'REFTABLE': u'',
                                    u'REPTEXT': u'COAr',
                                    u'ROLLNAME': u'KOKRS',
                                    u'SCRLEN1': 10,
                                    u'SCRLEN2': 15,
                                    u'SCRLEN3': 20,
                                    u'SCRTEXT_L': u'Controlling Area',
                                    u'SCRTEXT_M': u'CO Area',
                                    u'SCRTEXT_S': u'CO Area',
                                    u'SIGN': u'',
                                    u'TABNAME': u'CSKS',
                                    'TOPSHLPFLD': u'',
                                    'TOPSHLPNAM': u'',
                                    u'VALEXI': u''}

    assert eh['FIELDDESCR'][2] =={ u'AUTHORID': u'',
                                    u'BIDICTRLC': u'',
                                    u'CHECKTABLE': u'',
                                    u'COMPTYPE': u'E',
                                    u'CONVEXIT': u'ALPHA',
                                    u'DATATYPE': u'CHAR',
                                    u'DECIMALS': 0,
                                    u'DOMNAME': u'KOSTL',
                                    u'DYNPFLD': u'X',
                                    u'F4AVAILABL': u'X',
                                    u'FIELDNAME': u'KOSTL',
                                    u'FIELDTEXT': u'Cost Center',
                                    u'GENKEY': u'',
                                    u'HEADLEN': 10,
                                    u'INTLEN': 20,
                                    u'INTTYPE': u'C',
                                    u'KEYFLAG': u'X',
                                    u'LANGU': u'E',
                                    u'LENG': 10,
                                    u'LFIELDNAME': u'KOSTL',
                                    u'LOGFLAG': u'X',
                                    u'LOWERCASE': u'',
                                    u'LTRFLDDIS': u'',
                                    u'MAC': u'X',
                                    u'MASK': u'',
                                    u'MASKLEN': u'0000',
                                    u'MEMORYID': u'KOS',
                                    u'NOAUTHCH': u'',
                                    u'NOFORKEY': u'',
                                    u'OFFSET': 14,
                                    u'OUTPUTLEN': 10,
                                    'PARTXT': '',
                                    'PARVA': '',
                                    u'POSITION': 3,
                                    u'PRECFIELD': u'CSKS',
                                    u'REFFIELD': u'',
                                    u'REFTABLE': u'',
                                    u'REPTEXT': u'Cost Ctr',
                                    u'ROLLNAME': u'KOSTL',
                                    u'SCRLEN1': 10,
                                    u'SCRLEN2': 15,
                                    u'SCRLEN3': 20,
                                    u'SCRTEXT_L': u'Cost Center',
                                    u'SCRTEXT_M': u'Cost Center',
                                    u'SCRTEXT_S': u'Cost Ctr',
                                    u'SIGN': u'',
                                    u'TABNAME': u'CSKS',
                                    'TOPSHLPFLD': u'',
                                    'TOPSHLPNAM': u'',
                                    u'VALEXI': u''}


    # sel = []
    # r = vih.search('CT CSKS', [])
    # _todo: this is unusual, 3 interfaces returned, no headers ... check


    # sel = []
    # result = r.search('CSKS', sel)
    # search_result = result['search_result']
    # headers = result['headers']
    # assert headers == [[u'KOKRS', u'COAr', 4],
    #                   [u'KOSTL', u'Cost Ctr', 10],
    #                   [u'DATBI', u'to', 8],
    #                   [u'KTEXT', u'Name', 20]]
    # assert len(search_result) == 2332



def test_CT_T501():
    # Employee group (from CAPS)
    shlpname = 'CT T501'
    d = vih.get_shelp_descriptor(shlpname)
    r = vih.search(shlpname, [])

    assert r['headers'] == [[u'PERSG', u'EEGrp', 1], [u'PTEXT', u'Name of EE group', 20]]
    assert r['search_result'] == [
        {u'PERSG': u'1', u'PTEXT': u'Active'},
        {u'PERSG': u'2', u'PTEXT': u'Retiree/pensioner'},
        {u'PERSG': u'3', u'PTEXT': u'Permanent PT'},
        {u'PERSG': u'4', u'PTEXT': u'Contractors/3rd prty'},
        {u'PERSG': u'5', u'PTEXT': u'Terminated'},
        {u'PERSG': u'6', u'PTEXT': u'Casuals'},
        {u'PERSG': u'7', u'PTEXT': u'Temp/Seasonal FT'},
        {u'PERSG': u'8', u'PTEXT': u'Temporary PT'},
        {u'PERSG': u'9', u'PTEXT': u'External (substit.)'},
        {u'PERSG': u'A', u'PTEXT': u'Permanent'},
        {u'PERSG': u'C', u'PTEXT': u'External (substit.)'},
        {u'PERSG': u'E', u'PTEXT': u'Expatriate'},
        {u'PERSG': u'I', u'PTEXT': u'Inpatriate'},
        {u'PERSG': u'V', u'PTEXT': u'Volunteer'}]

    assert r['desc'][0] == {u'AUTHORID': u'',
                            u'BIDICTRLC': u'',
                            u'CHECKTABLE': u'',
                            u'COMPTYPE': u'E',
                            u'CONVEXIT': u'',
                            u'DATATYPE': u'CHAR',
                            u'DECIMALS': u'000000',
                            u'DOMNAME': u'PERSG',
                            u'DYNPFLD': u'X',
                            u'F4AVAILABL': u'',
                            u'FIELDNAME': u'PERSG',
                            u'FIELDTEXT': u'Employee Group',
                            u'GENKEY': u'',
                            u'HEADLEN': u'05',
                            u'INTLEN': u'000002',
                            u'INTTYPE': u'C',
                            u'KEYFLAG': u'X',
                            u'LANGU': u'E',
                            u'LENG': u'000001',
                            u'LFIELDNAME': u'PERSG',
                            u'LOGFLAG': u'X',
                            u'LOWERCASE': u'',
                            u'LTRFLDDIS': u'',
                            u'MAC': u'',
                            u'MASK': u'',
                            u'MASKLEN': u'0000',
                            u'MEMORYID': u'PRG',
                            u'NOAUTHCH': u'',
                            u'NOFORKEY': u'',
                            u'OFFSET': u'000006',
                            u'OUTPUTLEN': u'000001',
                            u'POSITION': u'0001',
                            u'PRECFIELD': u'T501',
                            u'REFFIELD': u'',
                            u'REFTABLE': u'',
                            u'REPTEXT': u'EEGrp',
                            u'ROLLNAME': u'PERSG',
                            u'SCRLEN1': u'10',
                            u'SCRLEN2': u'12',
                            u'SCRLEN3': u'20',
                            u'SCRTEXT_L': u'Employee group',
                            u'SCRTEXT_M': u'EE group',
                            u'SCRTEXT_S': u'EE group',
                            u'SIGN': u'',
                            u'TABNAME': u'T501',
                            u'VALEXI': u''}

    assert r['desc'][1] =={ u'AUTHORID': u'',
                            u'BIDICTRLC': u'',
                            u'CHECKTABLE': u'',
                            u'COMPTYPE': u'E',
                            u'CONVEXIT': u'',
                            u'DATATYPE': u'CHAR',
                            u'DECIMALS': u'000000',
                            u'DOMNAME': u'TEXT20',
                            u'DYNPFLD': u'X',
                            u'F4AVAILABL': u'',
                            u'FIELDNAME': u'PTEXT',
                            u'FIELDTEXT': u'Name of Employee Group',
                            u'GENKEY': u'',
                            u'HEADLEN': u'18',
                            u'INTLEN': u'000040',
                            u'INTTYPE': u'C',
                            u'KEYFLAG': u'X',
                            u'LANGU': u'E',
                            u'LENG': u'000020',
                            u'LFIELDNAME': u'PTEXT',
                            u'LOGFLAG': u'',
                            u'LOWERCASE': u'X',
                            u'LTRFLDDIS': u'',
                            u'MAC': u'',
                            u'MASK': u'',
                            u'MASKLEN': u'0000',
                            u'MEMORYID': u'',
                            u'NOAUTHCH': u'',
                            u'NOFORKEY': u'',
                            u'OFFSET': u'000008',
                            u'OUTPUTLEN': u'000020',
                            u'POSITION': u'0002',
                            u'PRECFIELD': u'T501T',
                            u'REFFIELD': u'',
                            u'REFTABLE': u'',
                            u'REPTEXT': u'Name of EE group',
                            u'ROLLNAME': u'PGTXT',
                            u'SCRLEN1': u'10',
                            u'SCRLEN2': u'15',
                            u'SCRLEN3': u'20',
                            u'SCRTEXT_L': u'Name of employee grp',
                            u'SCRTEXT_M': u'Name of EE grp',
                            u'SCRTEXT_S': u'EE gp name',
                            u'SIGN': u'',
                            u'TABNAME': u'T501T',
                            u'VALEXI': u''}

    assert r['shlpoutput'] == u'PERSG'


#
# tear down
#

